version: '3.4'
services:
  pharmacy-back:
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
    container_name: pharmacy-back
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    stop_signal: SIGKILL
    privileged: true
    stdin_open: true
    tty: true
    entrypoint: ['npm', 'run', 'start:dev']
    restart: 'always'
    environment:
      - DB_HOST=postgres-service
    depends_on:
      - postgres-service

  postgres-service:
    image: 'postgres:13-alpine'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -p 5432 -U root -d pharmacy',
        ]
      interval: 20s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pharmacy
    stop_signal: SIGKILL